// Package lfsr implements pseudo random number generators based on linear feedback shift registers (LFSR).
//
// Random numbers generated by the LFSR implemented in this package will produce a sequence that has a period covering the full range of bits for the chosen LFSR.
// A well desing n bit LFSR that will return the numbers in the range 1-2^n in a pseudo random order with no repeating numbers until the full range has been exhausted.
// In this package the following linear feedback registers are provided:
// Lfsr8 - 8 bit LFSR with a period of 255
// Lfsr16 - 16 bit LFSR with a period of 65,535
// Lfsr32 - 32 bit LFSR with a period of 4,294,967,296
// Lfsr64 - 64 bit LFSR with a period of 18,446,744,073,709,551,616
package lfsr
